[package]
name = "ch07-host"
version = "0.1.0"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = "1.0.104"
wasmtime = { version = "48.0.0", default-features = false, features = ["anyhow", "component-model", "cranelift", "runtime", "std"] }
wasmtime-wasi = { version = "48.0.0", default-features = false, features = ["p2"] }

[lints]
workspace = true
